language: node_js
node_js:
- node
script:
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_341d75a1b70c_key -iv $encrypted_341d75a1b70c_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
after_success:
- .travis/deploy.sh