title: Boothby
logo: https://raw.githubusercontent.com/Thomah/boothby/master/public/img/Photo-Boothby.png
description: A Slack Bot to raise awareness on a topic
show_downloads: true
theme: jekyll-theme-minimal
